export default function Gallery() {
  return (
    <>
      <h1>Gallery</h1>
      <p className="lead">
        Images are the other asset type a project holds (alongside documents),
        and the Gallery is where you browse, preview, and manage them. Images
        can be generated by any AI model during a chat conversation or added to
        the project manually, and every model in the project sees the same
        gallery.
      </p>

      <h2>Image Grid</h2>
      <p>
        The left sidebar displays all project images as a thumbnail grid. Click
        any image to select it and view it in full size in the main panel. The
        selected image is highlighted with a border.
      </p>

      <h2>Full Preview</h2>
      <p>
        When an image is selected, the center panel shows a large preview that
        scales to fit the available space. The image name is displayed in the
        header above the preview.
      </p>

      <h2>Tabs</h2>
      <p>
        Like documents, images can be opened in tabs for quick switching between
        multiple images. Tabs support:
      </p>
      <ul>
        <li>Renaming via right-click context menu</li>
        <li>Closing with the X button</li>
        <li>Horizontal scrolling when many tabs are open</li>
      </ul>

      <h2>Managing Images</h2>
      <p>
        Right-click any image in the sidebar or tab bar to access these options:
      </p>
      <ul>
        <li>
          <strong>Rename</strong> &mdash; change the image filename.
        </li>
        <li>
          <strong>Delete</strong> &mdash; remove the image from the project.
          Respects your trash preference (move to Trash or delete permanently).
        </li>
      </ul>

      <h2>AI-Generated Images</h2>
      <p>
        Image generation is a two-step, picker-driven flow so you stay in
        control of which model is used regardless of which model you&apos;re
        chatting with:
      </p>
      <ol>
        <li>
          Ask any model in chat to generate, create, or make an image. You can
          describe the subject in the same message, or work it out
          conversationally first.
        </li>
        <li>
          The model responds by opening an image configuration form inline in
          the chat. You pick the image model, dimensions, and quality or
          resolution. Current options include OpenAI&apos;s GPT Image family and
          Google&apos;s Nano Banana (Gemini) models.
        </li>
        <li>
          Once you confirm your selections, the model generates the image with
          those settings and saves it straight to the project gallery. New
          images appear in the sidebar automatically.
        </li>
      </ol>
      <p>
        Generated images carry metadata about the prompt and settings that
        produced them, so you can always trace an image back to how it was made.
      </p>
    </>
  );
}
